# This is a basic workflow to help you get started with Actions

name: RasaCIJob2

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  data-validation:
    name: Data Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pull request HEAD commit instead of merge commit 
      uses: actions/checkout@v2
      if: github.event_name == 'pull_request'
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Checkout git repository
      uses: actions/checkout@v2
      if: github.event_name != 'pull_request'
      
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade "pip<20"
        pip install -r requirements.txt
    - name: Rasa Data Validation
      run: |
        rasa data validate --debug
  training-testing:
    name: Test Model
    runs-on: ubuntu-latest
    needs: 
    - data-validation
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout pull request HEAD commit instead of merge commit 
      uses: actions/checkout@v2
      if: github.event_name == 'pull_request'
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Checkout git repository
      uses: actions/checkout@v2
      if: github.event_name != 'pull_request'
      
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
          python -m pip install --upgrade "pip<20"
          pip install -r requirements.txt
          rasa --version
    - name: Cross-validate NLU model
      id: cvnlu
      if: contains( github.event.pull_request.labels.*.name, 'nlu_testing_required' ) 
      run: |
          rasa --version
          rasa test nlu -f 3 --cross-validation --config config.yml
          python .github/workflows/format_results.py
    - name: post cross-val results to PR
      if: steps.cvnlu.outcome == 'success'
      uses: amn41/comment-on-pr@comment-file-contents
      continue-on-error: true
      with:
        msg: results.md
    - name: Train Model
      run: |
        rasa --version
        rasa train
    - name: Test End 2 End Stories
      run: |
        rasa --version
        rasa test core --stories tests/test_conversations.yml --fail-on-prediction-errors
 
